### ISSUE TITLE
Allure reporter with video - Cannot use import statement outside a module

### ISSUE THREAD

**Issue by PavanMudigondaTR** [svierk/salesforce-utam-e2e-testing#68]
I have a bit of trouble adding Allure reporter with video. I kept getting error about 

https://webdriver.io/docs/wdio-video-reporter/

* i cloned this repo 
* added below to wdio.conf.js
const video = require('wdio-video-reporter');

* also i added reporter
 reporters: [
    [video, {
      saveAllVideos: false,       // If true, also saves videos for successful test cases
      videoSlowdownMultiplier: 3, // Higher to get slower videos, lower for faster videos [Value 1-100]
    }],
    ['allure', {
      outputDir: './_results_/allure-raw',
      disableWebdriverStepsReporting: true,
      disableWebdriverScreenshotsReporting: true,
    }],
  ],

Errror

(node:59167) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
2024-03-16T22:47:11.828Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: file:///Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/wdio.conf.js: Cannot use import statement outside a module
/Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/node_modules/wdio-video-reporter/dist/wdio-video-reporter.mjs:1
import os from 'node:os';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._compile (/Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .mjs] (/Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/wdio.conf.js:8:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (/Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/node_modules/pirates/lib/index.js:117:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .js] (/Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/node_modules/pirates/lib/index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at ConfigParser.addConfigFile (file:///Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/node_modules/@wdio/config/build/node/ConfigParser.js:94:36)
    at ConfigParser.initialize (file:///Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/node_modules/@wdio/config/build/node/ConfigParser.js:56:13)
    at Launcher.run (file:///Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/node_modules/@wdio/cli/build/launcher.js:41:9)
    at Module.run (file:///Users/pavanmudigonda/Documents/utam-demo/salesforce-utam-e2e-testing/node_modules/@wdio/cli/build/run.js:64:20)

 *  The terminal process "/bin/zsh '-l', '-c', 'npm run test:ui'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 *

**Comment by svierk** [comment]
Hi @PavanMudigondaTR,
I must admit that I have not used this Video Reporter before that also seems to be a 3rd party package. But I tried to use it now because of your issue, but I get the identical error. This kind of error usually results from the use of import syntax for modules written in ECMAScript (ES) when Node.js is expecting the require keyword used by CommonJS modules which also seems to be the case here.


Apart from that, the Allure Reporter itself works perfectly fine. I also got it to run easily using the steps described here:
https://webdriver.io/docs/allure-reporter/

This then generates the Allure test results as follows without issues:
<img width="1042" alt="image" src="https://github.com/svierk/salesforce-utam-e2e-testing/assets/16227041/df477442-06b2-4176-ac85-fe912a32178d">

However, since the problem you described is not related directly to the contents of this UTAM template repo here, but rather seems to be a general problem with WebdriverIO and this Video Reporter package, I would close the issue here and rather suggest to open one at the Video Reporter repo itself.
